[build]
  command = "curl -LsSf https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C /usr/local/bin && trunk build --release"
  publish = "dist"

[[headers]]
  for = "/*.wasm"
  [headers.values]
  Content-Type = "application/wasm"